python ../code/synbad.py basefile=synbad dochtml newlog

echo '#' $(python ../code/synbad.py --description) > ../SynBad.md
echo >> ../SynBad.md

echo '```' >> ../SynBad.md
python ../code/synbad.py --details >> ../SynBad.md
echo '```' >> ../SynBad.md
echo >> ../SynBad.md
echo 'For a better rendering and navigation of this document, please download and open [`./docs/synbad.docs.html`](./docs/synbad.docs.html), or visit <https://slimsuite.github.io/synbad/>.' >> ../SynBad.md
echo 'Documentation can also be generated by running SynBad with the `dochtml=T` option. (R and pandoc must be installed - see below.)' >> ../SynBad.md
echo >> ../SynBad.md
echo '## Introduction' >> ../SynBad.md
echo >> ../SynBad.md
grep -A 10000 tool synbad.docs.Rmd >> ../SynBad.md

cp synbad.docs.html ../index.html
cp ../SynBad.md ../README.md

ls -lrth ../
ls -lrth
